// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KYBiDxGoS7WgTnMErjP4BEkAL1-lvWY',
    appId: '1:406278527465:web:ad226cf5456ec56861d378',
    messagingSenderId: '406278527465',
    projectId: 'chatnest2',
    authDomain: 'chatnest2.firebaseapp.com',
    storageBucket: 'chatnest2.firebasestorage.app',
    measurementId: 'G-HRQVVXDHV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82tTHofC8a09B6fcP34KVuQXAWM1pzyo',
    appId: '1:406278527465:android:c1a3b402d7257fe661d378',
    messagingSenderId: '406278527465',
    projectId: 'chatnest2',
    storageBucket: 'chatnest2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9EmnWZ2bMnc2RhNmiPbyKkAIiJtUKBC0',
    appId: '1:406278527465:ios:42249a0bf88b89a161d378',
    messagingSenderId: '406278527465',
    projectId: 'chatnest2',
    storageBucket: 'chatnest2.firebasestorage.app',
    iosBundleId: 'com.example.version2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9EmnWZ2bMnc2RhNmiPbyKkAIiJtUKBC0',
    appId: '1:406278527465:ios:42249a0bf88b89a161d378',
    messagingSenderId: '406278527465',
    projectId: 'chatnest2',
    storageBucket: 'chatnest2.firebasestorage.app',
    iosBundleId: 'com.example.version2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8KYBiDxGoS7WgTnMErjP4BEkAL1-lvWY',
    appId: '1:406278527465:web:0f0c385dd7ae8eb161d378',
    messagingSenderId: '406278527465',
    projectId: 'chatnest2',
    authDomain: 'chatnest2.firebaseapp.com',
    storageBucket: 'chatnest2.firebasestorage.app',
    measurementId: 'G-NV2G5WY1X5',
  );
}
